### ISSUE TITLE
Missing `__init__.py` and extra empty file in repo.

### ISSUE THREAD

**Issue by FoamyGuy** [adafruit/Adafruit_CircuitPython_IterTools#13]
This library is contains a package rather than a single `.py` file module. But the package is missing an `__init__.py` file in it's root so it's not being recognized as a package by other tools like mypy. I believe this is the root cause for #12 not getting it's description filled in properly.

Need to create `adafruit_itertools/__init__.py` to resolve.

There is also an extra empty file in this repo `adafruit_itertools/adafruit_itertools`: https://github.com/adafruit/Adafruit_CircuitPython_IterTools/blob/main/adafruit_itertools/adafruit_itertools

It does not seem to be used for anything as far as I can tell. It's existence probably does not cause any specific harm, but I think it could be safely removed.

**Comment by earthprelude** [comment]
Can I help with this?

**Comment by BodaleDenis** [comment]
Hi, I'm a beginner to contributing for open source.
I would like to start with this if it's Ok.
Thank you and best regards

**Comment by FoamyGuy** [comment]
> Can I help with this?

@earthprelude yes you can make a PR with these changes. If you are new to contributing with GitHub we have a guide that covers th eprocess here: https://learn.adafruit.com/contribute-to-circuitpython-with-git-and-github.

@BodaleDenis let's let earthprelude get this one since they were here first. We have recently created many other `good first issue`s across the various libraries to add type annotations. Those and other items we've identified as good first issues get listed here: https://circuitpython.org/contributing/open-issues?label=good-first-issue. It's updated once per day so tomorrow it should have all of the type annotation ones. In the meantime they can be found in the issues section for nearly every CircuitPython library.

**Comment by earthprelude** [comment]
Thanks for the guide!
