### ISSUE TITLE
Move library code out of inner directory

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_IterTools#15]
From Dave Astels:
There's something wrong with the adafruit_itertools build/packaging. Using the source from GitHub works, but the dir/mpy in the bundle doesn't... it just imports empty.

Please see https://forums.adafruit.com/viewtopic.php?f=65&t=191711

From Kattni:
I tried importing `islice` using the GitHub source code, and it failed. I see it in the file, it exists, but it's not importing evidently. Dave originally included running `dir(adafruit_itertools)` from the REPL as proof that it was importing empty, but even the GitHub source code only shows `['__class__', '__name__', '__file__', '__path__']`. I am unsure whether it is supposed to show more.

**Comment by kattni** [comment]
Turns out the import structure for IterTools is `import adafruit_itertools.adafruit_itertools`. Thank you to Neradoc on Discord for catching this.

```
>>> import adafruit_itertools.adafruit_itertools
>>> dir(adafruit_itertools.adafruit_itertools)
['__class__', '__name__', 'count', '__file__', '__version__', 'chain', 'compress', '__repo__', 'accumulate', 'chain_from_iterable', 'combinations', 'combinations_with_replacement', 'cycle', 'dropwhile', 'filterfalse', 'groupby', 'islice', 'permutations', 'product', 'repeat', 'starmap', 'takewhile', 'tee', 'zip_longest']
>>>
```

**Comment by caternuson** [comment]
Is this just import syntax confusion? The folder is the same name as one of the modules.

Don't import the folder:
```python
Adafruit CircuitPython 7.3.0 on 2022-05-23; Adafruit CLUE nRF52840 Express with nRF52840
>>> import adafruit_itertools
>>> dir(adafruit_itertools)
['__class__', '__name__', '__file__', '__path__']
>>> 
```

import the module:

```python
Adafruit CircuitPython 7.3.0 on 2022-05-23; Adafruit CLUE nRF52840 Express with nRF52840
>>> from adafruit_itertools import adafruit_itertools
>>> dir(adafruit_itertools)
['__class__', '__name__', 'count', '__file__', '__version__', 'chain', 'compress', '__repo__', 'accumulate', 'chain_from_iterable', 'combinations', 'combinations_with_replacement', 'cycle', 'dropwhile', 'filterfalse', 'groupby', 'islice', 'permutations', 'product', 'repeat', 'starmap', 'takewhile', 'tee', 'zip_longest']
>>>  
```

**Comment by dhalbert** [comment]
I believe this is basically a bug. In CPython, regular `itertools` functionality is not two levels down.
```py
Python 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import itertools
>>> dir(itertools)
['__doc__', '__loader__', '__name__', '__package__', '__spec__', '_grouper', '_tee', '_tee_dataobject', 'accumulate', 'chain', 'combinations', 'combinations_with_replacement', 'compress', 'count', 'cycle', 'dropwhile', 'filterfalse', 'groupby', 'islice', 'pairwise', 'permutations', 'product', 'repeat', 'starmap', 'takewhile', 'tee', 'zip_longest']
```
