### ISSUE TITLE
AttributeError, adafruit_itertools dependencies not loaded by adafruit_itertools_extras 

### ISSUE THREAD

**Issue by paretech** [adafruit/Adafruit_CircuitPython_IterTools#3]
Dependencies from adafruit_itertools.adafruit_itertools, needed by adafruit_itertools.adafruit_itertools_extras not loaded resulting in AttributeError. To reproduce run the following. 

```python
from adafruit_itertools.adafruit_itertools import count
from adafruit_itertools.adafruit_itertools_extras import take

take(1, count(1, 5))
```

```sh
>>> import issues.itertools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/issues/itertools.py", line 5, in <module>
  File "adafruit_itertools/adafruit_itertools_extras.py", line 341, in take
AttributeError: 'module' object has no attribute 'islice'
```

Adafruit CircuitPython 4.1.0 on 2019-08-02; Adafruit CircuitPlayground Express with samd21g18
adafruit-circuitpython-bundle-4.x-mpy-20190816

**Comment by jepler** [comment]
@paretech thanks for your report.  I believe I've identified the problem and a fix.
